# Generated by Django 4.1.1 on 2022-10-31 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_books_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='price',
        ),
    ]
