# Generated by Django 4.1.1 on 2022-11-16 14:30

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_remove_books_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='books',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
