# Generated by Django 4.1.1 on 2022-11-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_books_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='books',
        ),
        migrations.RemoveField(
            model_name='books',
            name='name',
        ),
        migrations.AddField(
            model_name='books',
            name='book_id',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='books',
            name='cover_image',
            field=models.URLField(default='0'),
        ),
        migrations.AddField(
            model_name='books',
            name='title',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='books',
            name='url',
            field=models.URLField(default='0'),
        ),
    ]
